### ISSUE TITLE
configure: error: Please install SDL2_gfx >= 1.0.0

### ISSUE THREAD

**Issue by Mailaender** [lincity-ng/lincity-ng#104]
I was trying to create a @flathub package https://github.com/lincity-ng/lincity-ng/issues/33, but I am stuck because your build system does not detect dependencies getting installed into `/app` as it seems.

```yaml
app-id: com.github.lincity_ng.lincity_ng
runtime: org.freedesktop.Platform
runtime-version: '23.08'
sdk: org.freedesktop.Sdk

[...]

  - name: SDL2_gfx
    buildsystem: autotools
    build-options:
      all:
        --disable-static
      arch:
        aarch64:
          config-opts:
            - --disable-mmx
    sources:
      - type: archive
        url: https://downloads.sf.net/sdl2gfx/SDL2_gfx-1.0.4.tar.gz
        sha256: 63e0e01addedc9df2f85b93a248f06e8a04affa014a835c2ea34bfe34e576262
      - type: shell
        commands:
          - cp -p /usr/share/automake-*/config.{sub,guess} .
          - autoreconf -fvi

  - name: lincity-ng
    buildsystem: automake
    build-commands:
      - ./autogen.sh
      - ./configure --prefix=${FLATPAK_DEST} --with-libSDL2_gfx=${FLATPAK_DEST}/lib
      - jam
      - jam -sprefix=${FLATPAK_DEST} install
    sources:
      - type: git
        url: https://github.com/lincity-ng/lincity-ng
        tag: lincity-ng-2.9.0
        commit: ff3e337bf2904fb3f11026be232327cb1624a332
        x-checker-data:
          type: git
          tag-pattern: ^lincity-ng-([\d.]+)$
```

results in
> configure: error: Please install SDL2_gfx >= 1.0.0

which I don't know how to workaround.
